pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/spring-guides/gs-actuator-service.git'
                dir('complete'){
                    sh 'pwd'
                    sh 'docker build .'
                }
            }
        }
        stage('ZAP') {
            steps {
                script {
                    startZap(host: "127.0.0.1", port: 9991 , timeout: 500, zapHome: "/opt/zaproxy")
                }
            }
        }
    }
}