pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/iam-dev/gs-actuator-service.git'
                dir('complete'){
                    sh 'pwd'
                    sh 'docker build --tag gs-actuator-service .'
                }
            }
        }
        stage('ZAP') {
            steps {
                script {
                    startZap(host: "127.0.0.1", port: 9991 , timeout: 500, zapHome: "/opt/zaproxy")
                }
            }
        }
        stage('Docker Run') {
            steps {
             sh '''
                if [ ! "$(docker ps -q -f name=gs-actuator-service)" ]; then
                    if [ "$(docker ps -aq -f status=exited -f name=gs-actuator-service)" ]; then
                        # cleanup
                            docker rm gs-actuator-service
                    fi
                    # run your container
                        docker run --publish 8080:8080 --detach --name gs-actuator-service gs-actuator-service
                fi
                '''
            }
        }
        stage('Run ZAP Attack') {
            steps {
                script {
                    runZapCrawler(host: "http://localhost:8080")
                }
            }
        }
    }
}